### ISSUE TITLE
devkit doesn't build with OCaml 4.03.0 onwards (duplicate exception definitions)

### ISSUE THREAD

**Issue by yallop** [ahrefs/devkit#1]
The error is as follows:

```
# File "devkit_ragel.ml", line 350, characters 10-20:
# Error: Multiple definition of the extension constructor name Goto_match.
#        Names must be unique in a given structure or signature.
# Command exited with code 2.
```

**Comment by yallop** [comment]
I've added a constraint in `opam-repository`: https://github.com/ocaml/opam-repository/pull/8247

**Comment by ygrek** [comment]
Thanks for the heads up!
Fixed in new release - https://github.com/ocaml/opam-repository/pull/8295
